### ISSUE TITLE
Project not found issue when the organization is null

### ISSUE THREAD

**Issue by mpgxvii** [RADAR-base/radar-jersey#75]
- The issue happens when using a previous version of `Managementportal` <2.0.0, `radar-jersey` 0.10.0, and `rest-sources-auth` 4.3.0.
- When trying to get projects or users in a project from `ProjectService`, it returns `project_not_found` error, even when the project exists.
- Logs from `rest-sources-authorizer-backend`:
```
ERROR - [404] GET projects/STAGING_PROJECT/users - project_not_found: Project STAGING_PROJECT not found in Management Portal. (HttpApplicationExceptionMapper.kt:30)
```
- Since old versions of MP doesn't have the organization structure (organization for the specific project is null), checking permissions of the user for the project causes a `project_not_found` error. This is because it checks the organization first then if the organization is null, it says the project does not exist. 
- Getting the project organization for the project throws an error here: https://github.com/RADAR-base/radar-jersey/blob/d639844ef8f4c42ea10f4caaeabd2c7f57cf93be/radar-jersey/src/main/kotlin/org/radarbase/jersey/auth/filter/PermissionFilter.kt#L88

**Comment by yatharthranjan** [comment]
I believe the aim was to keep it backwards compatible. In order to do so we can add a new project service implementation that does support old MP instances and that can be dynamically configured at runtime in downstream clients (like rest-sources-auth). Alternatively, we can allow null in the current code, but i would not prefer it as it is not correct for new MP versions.

**Comment by blootsvoets** [comment]
The suggestion from @yatharthranjan sounds good to me. It will then need to be configured for underlying services which MP version is being used.

**Comment by blootsvoets** [comment]
Alternatively, the implementation does a fallback -- if the `organizations` endpoint is reachable, use the new implementation, otherwise accept `null` organisation.
